### ISSUE TITLE
provide renderer

### ISSUE THREAD

**Issue by dbu** [rokka-io/rokka-client-php#12]
we should offer a renderer similar to https://github.com/rokka-io/rokka.js#render (and the symfony bundle should offer this as a twig function too)

**Comment by chregu** [comment]
There will be one in the upcoming twig bundle (and some helper classes in this rokka-client-php), see https://github.com/rokka-io/rokka-client-php/tree/templatehelper for the WIP branch

**Comment by chregu** [comment]
This is actually done and merged now
